### ISSUE TITLE
[1.12.1] Ceramics Clay Bucket Duping

### ISSUE THREAD

**Issue by MasterEnderman** [PaleoCrafter/VanillaImmersion#19]
If you rightclick a claybucket filled with a liquid on a vanilla immersion crafting table, it places the liquid on top and puts an empty bucket on the crafting grid. The bucket ist duplicated by this. The vanilla (iron) bucket is working fine.

Minecraft: 1.12.1
Forge: 14.22.0.2467
Vanilla Immerison: 2.0.3.4

**Comment by marvin-roesch** [comment]
Hm, the mod should cancel all item interactions. I'll have to look into the Clay Bucket's behaviour to see if it tries to receive cancelled events.

**Comment by marvin-roesch** [comment]
Oh, I see you're using version 2.0.3.4 of the mod. Would you mind trying out the latest one (2.0.2.4)? It's a little confusing that there's a separate 1.12.1 version of the mod up on CurseForge right now, I'll actually remove it since I decided against separately maintaining a version of the mod for a minor game version that isn't much different. The 1.12 version will work just fine on 1.12.

**Comment by MasterEnderman** [comment]
As already said in the other issue this doesn't happen anymore. Thanks for the fix again.
