### ISSUE TITLE
crash with Better foliage 1.9.4

### ISSUE THREAD

**Issue by MrEvilCookie** [PaleoCrafter/VanillaImmersion#7]
[crash-2016-06-25_10.11.49-client.txt](https://github.com/PaleoCrafter/VanillaImmersion/files/332929/crash-2016-06-25_10.11.49-client.txt)
I can't run minecraft after installing vanilla immersion and better foliage(

**Comment by Mysterizon** [comment]
I have to say its the same problem for me, 

this time its 1.10.2 with Vanilla Immersion and Better Foliage mod.. one thing for sure. its a conflicting between 2 mods. I will also report this problem with Better foliage mod as well.

**Comment by octarine-noise** [comment]
@PaleoCrafter 

Kotlin seems to be gaining traction, and since it's not provided by Forge like Scala is, everyone who uses it just shades it in, and relocates the classes to prevent version collisions.

Now, this is only my hypothesis at this point, but I believe the problem is that class relocation tools only know about and process the Java bytecode, and the extra metadata Kotlin has for its classes remain untouched. Then someone else's bundled Kotlin classes get classloaded before yours - for example mine, as I use a class transformer written in Kotlin and that comes way sooner in the loading lifecycle. The class and its metadata won't match up properly, and will lead to errors the moment you try to use something that's not 100% in Java-land, like Kotlin reflection.

LexManos is very firm about not including any more language support in Forge itself, so the ways I can see to fix this situation are:
* Don't use Kotlin reflection. (I never needed it, but still pretty limiting)
* Don't shade it in, but have a universally accepted (and maintained!) Kotlin adapter mod.
* Shade it in, but use a tool for relocation that is Kotlin-aware. (I don't know of one)
* Shade it in, but don't relocate. Just have a gentleman's agreement on which version to use, and hope for the best.

For the moment, I'm inclined to go with the last option, and just include 1.0.2 (or latest final) in the next version of BF without relocation.

**Comment by Mysterizon** [comment]
Ok have you read the crash report.. is there a way i can get it working? i am not sure what is causing it to not working?

**Comment by octarine-noise** [comment]
Not yet, I'll fix it in the next BetterFoliage release. It's just slow going as usual.

I think the issue can be closed.

**Comment by PaleoCrafter** [comment]
Welp, thanks for the fix on your side! Sorry for my inactivity as of late. Yeah, @octarine-noise. not relocating really is the best option at the moment unless you want to do it manually.
